### ISSUE TITLE
Updating to Current Version of Karma

### ISSUE THREAD

**Issue by chaughawout** [hatchteam/karma-trx-reporter#12]
Any plans to upgrade this reporter to work with the current version of Karma? I'm running into issues locally just trying it out of the box with version 1.7.0, and I'm curious.

**Comment by brtx** [comment]
Currently we are not actively working on this project and are not planning to upgrade it. However feel free to contribute, the previous integration point of Karma was quite simple, I assume if anything changed it's probably not that hard to adapt the code support the new version.

**Comment by brtx** [comment]
I just checked the change-log of Karma (https://github.com/karma-runner/karma/blob/master/CHANGELOG.md) to me it doesn't look like they did any major changes to the reporting interface, so the plug-in should still work fine. What makes you think it needs to be updated? What kind of issues are you running in?

**Comment by chaughawout** [comment]
I found an alternative reporter that provided what I needed.

I was running into issues where the reported would throw an error after the tests were finished. I'm not sure what it was complaining about and I don't have the stack trace anymore. Wish I could be more helpful.
