### ISSUE TITLE
Option to prepend className to the test name

### ISSUE THREAD

**Issue by longdinh2017** [hatchteam/karma-trx-reporter#13]
I am currently using the tool to generate jasmine test results. However, for failed tests, the class name is not shown anywhere which make it difficult to determine where the test failed.

Can the class name be prepended to the test name as an option? Refer to attachment as an example?

![karma test result](https://user-images.githubusercontent.com/32347852/30945291-d0730412-a440-11e7-8e7a-e8893ed48c03.png)

**Comment by brtx** [comment]
We are setting the class name attribute of the trx structure. I am not quite sure why it is not displayed entirely in your case.

Are you referring to JavaScript classes? When we wrote that plugin, this did not exist, or at least was not in wide use, so it may well be that this is not yet captured. So for sure, it would make sense to display that from my point of view.

We are not really actively working on this plugin anymore, however the code is quite easy to understand and should be easy to extend. Just have a look in the index.js file (https://github.com/hatchteam/karma-trx-reporter/blob/master/index.js). The class name attribute is created in line 134. You could check out how to include the class name there and create a pull request and we'll happily merge it for you and create a new npm package. Please try to include it in a backwards compatible way, so using some option if necessary, we don't want to break other peoples test runs ;-).

Cheers Stefan

**Comment by jonasbg** [comment]
Hi

Is it possible to write out the describe() description? My tests only write out the it() descriptions as reported by @longdinh2017 

@brtx would you recommand any other plugin for writing test reports to TFS?

Thanks
Jonas

**Comment by brtx** [comment]
maybe this one helps you?
https://github.com/hatchteam/karma-trx-reporter/pull/19
