### ISSUE TITLE
NPM versions do not match tags added on GitHub

### ISSUE THREAD

**Issue by sigurdvh** [hatchteam/karma-trx-reporter#6]
NPM points to version 0.2.6, which is missing from the tags in the repo (same as version 0.2.5). Also, I would love to get a published version on NPM that contains the linux fix that sits already in master.

**Comment by lehmamic** [comment]
We will have a look at it.

**Comment by lehmamic** [comment]
I added the the tag for v0.2.7 and 0v0.2.8 published a new version to npm.
