### ISSUE TITLE
Question: How do you integrate this with TFS Builds?

### ISSUE THREAD

**Issue by logankd** [hatchteam/karma-trx-reporter#7]
I have a build step (in the newer HTML, steps build) to run my Jasmine test in Karma. I've hooked up this nice trx reporter and get the trx file output when I run it locally.

I haven't figured out how to get the TFS build output to show me the results of this trx, instead of the 1 of 1 they output by default. Could someone give me some pointers?

Thanks,

Kevin

**Comment by logankd** [comment]
I've figured this out and will be posting an article soon.

**Comment by lehmamic** [comment]
Great. Just for the other people, you need to use the command line tools:https://msdn.microsoft.com/en-us/library/ms243151.aspx

**Comment by logankd** [comment]
Here's my article: http://bit.ly/KarmaWithTFSBuild

**Comment by brtx** [comment]
Nice article!
