### ISSUE TITLE
Option not to prepend browser name/version to test name

### ISSUE THREAD

**Issue by carlin-q-scott** [hatchteam/karma-trx-reporter#8]
I'm running tests using PhantomJS and Jasmine and every test name is prepended with the browser name and version. This is not at all desirable when using a single browser so I'd like a way to disable this feature.

**Comment by brtx** [comment]
There is, it's called shortTestName, check the code.

**Comment by lehmamic** [comment]
`module.exports = function(config) {
  config.set({
    reporters: ['progress', 'trx'],

    // the default configuration
    trxReporter: { outputFile: 'test-results.trx', shortTestName: true }
  });
};`

**Comment by carlin-q-scott** [comment]
Note that that option is not in the readme.md. Should I adjust the title of this to add it?
